### ISSUE TITLE
Beacon Pros in iOS not firing Enter/Exit events

### ISSUE THREAD

**Issue by teemnam** [kontaktio/kontakt-ios-sdk#35] opened 2016-12-06 04:40 UTC
I have beacon pros using iOS app and they are not firing the Enter/Exit events. My code for Enter/Exit work for all other beacon types from Kontakt but beacon pros are not getting detected. I got the region based enter/exit but not getting the specific to beacon.

**Comment by stoprocent** [comment] 2016-12-06 16:19
Hi 
I belive this issue is a duplicate of your ticket with our support on zendesk.
Closing :)

**Closed by stoprocent** 2016-12-06 16:19 UTC
Labels: duplicate
