### ISSUE TITLE
KTKEddystoneManager.centralState is always 0

### ISSUE THREAD

**Issue by pvaltorta** [kontaktio/kontakt-ios-sdk#57] opened 2018-01-26 11:57 UTC
When I check value of KTKEddystoneManager.centralState to verify if Bluetooth is on or off, value of property is always 0 (zero).
Do I need to call some other function to start Bluetooth state check?

**Comment by homoky** [comment] 2018-05-02 12:29
@pvaltorta Hello, we are facing same issue as you here and in #56 as well. Can you please tell us how did you solve this? Thank you for feedback.

**Comment by stoprocent** [comment] 2018-07-20 09:51
Duplicate of #56

**Closed by stoprocent** 2018-07-20 09:51 UTC

**Comment by nashfive** [comment] 2019-01-17 10:14
Got the same issue. Not a duplicate of #56
I have created #73
